# Generated by Django 5.2.15 on 2026-07-01 21:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('completed', 'Terminée'), ('abandoned', 'Abandonnée')], default='active', max_length=10)),
                ('is_practice', models.BooleanField(default=False)),
                ('question_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stars_awarded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xp_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('hearts_lost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unlocked', 'Déverrouillé'), ('completed', 'Terminé')], default='unlocked', max_length=10)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('best_score_pct', models.PositiveSmallIntegerField(default=0)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='content.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression de niveau',
                'verbose_name_plural': 'Progressions de niveau',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField()),
                ('time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.levelattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('due_at', models.DateTimeField()),
                ('last_result', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de révision',
                'verbose_name_plural': 'Items de révision',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('last_is_correct', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique question',
                'verbose_name_plural': 'Statistiques questions',
            },
        ),
        migrations.AddIndex(
            model_name='levelattempt',
            index=models.Index(fields=['user', 'level', 'status'], name='attempt_user_level_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='levelattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='levelattempt_one_active_per_user'),
        ),
        migrations.AddConstraint(
            model_name='levelprogress',
            constraint=models.UniqueConstraint(fields=('user', 'level'), name='levelprogress_user_level_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='questionattempt_attempt_question_unique'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'due_at'], name='reviewitem_user_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='reviewitem_user_question_unique'),
        ),
        migrations.AddIndex(
            model_name='userquestionstat',
            index=models.Index(fields=['user', 'last_is_correct', 'last_seen_at'], name='uqs_user_last_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='userquestionstat',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='userquestionstat_user_question_unique'),
        ),
    ]
