# Generated by Django 5.2.15 on 2026-07-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_levelattempt_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelattempt',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
    ]
