# Generated by Django 5.2.15 on 2026-07-01 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('xp_reward', models.PositiveSmallIntegerField(default=20)),
                ('question_count_target', models.PositiveSmallIntegerField(default=10)),
                ('kind', models.CharField(choices=[('normal', 'Normal'), ('boss', 'Boss')], default='normal', max_length=10)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_ref', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='passages/')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('color_hex', models.CharField(max_length=7)),
                ('icon', models.CharField(help_text="Nom d'icône Lucide (ex. flask-conical)", max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('session', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-year', 'session'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qtype', models.CharField(choices=[('single', 'Choix unique'), ('multi', 'Choix multiples'), ('true_false', 'Vrai / Faux')], max_length=10)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('exam_question_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('explanation_text', models.TextField(blank=True)),
                ('explanation_media', models.FileField(blank=True, null=True, upload_to='explanations/')),
                ('explanation_media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo'), ('lottie', 'Lottie')], max_length=10)),
                ('difficulty', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('external_ref', models.CharField(blank=True, help_text="Clé d'idempotence de l'import (external_id du fichier)", max_length=120, null=True, unique=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.exam')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.passage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='LevelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_questions', to='content.level')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_links', to='content.question')),
            ],
            options={
                'verbose_name': 'Question du niveau',
                'verbose_name_plural': 'Questions du niveau',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='content.subject'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.subject')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='level',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='content.unit'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('year', 'session', 'faculty'), name='exam_year_session_faculty_unique'),
        ),
        migrations.AddConstraint(
            model_name='levelquestion',
            constraint=models.UniqueConstraint(fields=('level', 'question'), name='levelquestion_level_question_unique'),
        ),
        migrations.AddConstraint(
            model_name='levelquestion',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='levelquestion_level_order_unique'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'is_active'], name='content_que_subject_fa60a7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='content_que_exam_id_1f122c_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('subject', 'order'), name='unit_subject_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='level_unit_order_unique'),
        ),
    ]
