# Generated by Django 5.2.15 on 2026-07-02 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Step 1/3 of the Track rollout on a LIVE dev DB with existing data:
    add Track/ProgramYear/ProgramSemester + Subject.track/program_semester
    as NULLABLE first. See 0003_seed_tracks_and_backfill (data migration)
    and 0004_subject_track_not_null (tightens the constraint) for the rest.
    """

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Semestre de programme',
                'verbose_name_plural': 'Semestres de programme',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Année de programme',
                'verbose_name_plural': 'Années de programme',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text="Nom d'icône Lucide (ex. graduation-cap)", max_length=40)),
                ('color_hex', models.CharField(max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='program_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='content.programsemester'),
        ),
        migrations.AddField(
            model_name='programsemester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='content.programyear'),
        ),
        migrations.AddField(
            model_name='programyear',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='content.track'),
        ),
        migrations.AddField(
            model_name='subject',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='content.track'),
        ),
        migrations.AddConstraint(
            model_name='programsemester',
            constraint=models.UniqueConstraint(fields=('year', 'order'), name='programsemester_year_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='programyear',
            constraint=models.UniqueConstraint(fields=('track', 'order'), name='programyear_track_order_unique'),
        ),
    ]
