# Generated by Django 5.2.15 on 2026-07-02 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0004_subject_track_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.track'),
        ),
    ]
