# Generated by Django 5.2.15 on 2026-07-07 10:26

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def dedupe_emails(apps, schema_editor):
    """Blank duplicate emails before the case-insensitive unique constraint lands.

    Existing data could hold two accounts with the same address (email was
    previously non-unique). Keep the earliest-registered account's email and
    blank the rest so the account isn't lost — it just loses email recovery
    until its owner sets a fresh address. Safe no-op on clean data.
    """
    User = apps.get_model("accounts", "User")
    from collections import defaultdict

    groups = defaultdict(list)
    for user in User.objects.exclude(email="").order_by("date_joined", "id"):
        groups[user.email.strip().lower()].append(user)
    for _addr, users in groups.items():
        for dupe in users[1:]:  # keep the first (earliest), blank the others
            dupe.email = ""
            dupe.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_active_track'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(dedupe_emails, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'used_at'], name='accounts_pa_user_id_ba1dfe_idx'),
        ),
    ]
