# Generated by Django 5.2.15 on 2026-07-01 21:47

import apps.gamification.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(choices=[('level_complete', 'Niveau terminé'), ('perfect_bonus', 'Bonus sans-faute'), ('first_clear_bonus', 'Bonus première complétion'), ('combo_bonus', 'Bonus combo'), ('practice', 'Révision'), ('challenge_win', 'Défi gagné'), ('achievement', 'Trophée'), ('legendary', 'Niveau légendaire')], max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement XP',
                'verbose_name_plural': 'Événements XP',
            },
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('hearts', models.PositiveSmallIntegerField(default=apps.gamification.models.default_hearts)),
                ('hearts_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('streak_current', models.PositiveSmallIntegerField(default=0)),
                ('streak_longest', models.PositiveSmallIntegerField(default=0)),
                ('streak_last_day', models.DateField(blank=True, null=True)),
                ('streak_freezes', models.PositiveSmallIntegerField(default=0)),
                ('review_hearts_earned_today', models.PositiveSmallIntegerField(default=0)),
                ('review_hearts_day', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'État joueur',
                'verbose_name_plural': 'États joueur',
            },
        ),
    ]
