# Generated by Django 5.2.15 on 2026-07-01 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('gamification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('icon', models.CharField(help_text="Nom d'icône Lucide (ex. medal)", max_length=40)),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Palier de ligue',
                'verbose_name_plural': 'Paliers de ligue',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='playerstate',
            name='review_graduated_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Nom d'icône Lucide", max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rule_type', models.CharField(choices=[('xp_total', 'XP total'), ('streak_days', 'Jours de série'), ('levels_completed', 'Niveaux terminés'), ('perfect_levels', 'Niveaux sans-faute'), ('subject_levels_completed', 'Niveaux par matière'), ('friends_count', "Nombre d'amis"), ('challenges_won', 'Défis gagnés'), ('legendary_count', 'Couronnes légendaires'), ('review_graduated', 'Questions diplômées en révision'), ('league_promoted', 'Promotion de ligue'), ('league_podium', 'Podium de ligue'), ('league_cedre_first', 'Premier en Ligue Cèdre'), ('daily_levels', 'Niveaux dans la journée'), ('time_window_level', 'Niveau dans une fenêtre horaire'), ('perfect_week', 'Semaine parfaite')], max_length=30)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='content.subject')),
            ],
            options={
                'verbose_name': 'Trophée',
                'verbose_name_plural': 'Trophées',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeagueWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Semaine de ligue',
                'verbose_name_plural': 'Semaines de ligue',
                'ordering': ['-starts_at'],
                'constraints': [models.UniqueConstraint(fields=('iso_year', 'iso_week'), name='leagueweek_iso_unique')],
            },
        ),
        migrations.CreateModel(
            name='LeagueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.PositiveSmallIntegerField(default=0)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='gamification.leaguetier')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gamification.leagueweek')),
            ],
            options={
                'verbose_name': 'Cohorte de ligue',
                'verbose_name_plural': 'Cohortes de ligue',
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_week', models.PositiveIntegerField(default=0)),
                ('xp_week_counted', models.PositiveIntegerField(default=0)),
                ('counted_day', models.DateField(blank=True, null=True)),
                ('counted_today', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('promoted', 'Promu·e'), ('stayed', 'Maintenu·e'), ('demoted', 'Rétrogradé·e')], max_length=10, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gamification.leaguegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adhésion de ligue',
                'verbose_name_plural': 'Adhésions de ligue',
                'indexes': [models.Index(fields=['group', '-xp_week_counted'], name='league_group_counted_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='leaguemembership_user_group_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trophée débloqué',
                'verbose_name_plural': 'Trophées débloqués',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='userachievement_user_achievement_unique')],
            },
        ),
    ]
